server:
  port: 9003
spring:
#  rabbitmq:
#    host: 192.168.11.129
  application:
    name: qian-an-personalCenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qian_an?characterEncoding=UTF8
    username: root
    password: root
  jpa:
    database: Mysql
    show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    # 加盐
    key: qianAn
    ttl: 3600000
