server:
  port: 10010
spring:
#  rabbitmq:
#    host: 192.168.11.129
  application:
    name: qian-an-web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    qian-an-menu:
      path: /cook/**
      serviceId: qian-an-menu
    qian-an-personalCenter:
      path: /center/**
      serviceId: qian-an-personalCenter
    qian-an-upload:
      path: /upload/**
      serviceId: qian-an-upload
    qian-an-spit:
      path: /spit/**
      serviceId: qian-an-spit
    qian-an-search:
      path: /search/**
      serviceId: qian-an-search
