server:
  port: 9004
spring:
  rabbitmq:
    host: 192.168.11.129
  application:
    name: qian-an-chat
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
socketio:
  port: 9988
  upgradeTimeout: 3000
  pingInterval: 25000
  pingTimeout: 8000
feign:
  hystrix:
    enabled: true
