server:
  port: 10086
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
#spring:
#  rabbitmq:
#    host: 192.168.11.129
