server:
  port: 9006
spring:
  rabbitmq:
    host: 192.168.11.129
  application:
    name: qian-an-search
  data:
    elasticsearch:
      cluster-nodes: 192.168.11.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
