server:
  port: 9001
spring:
  application:
    name: qian-an-menu
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/qian_an?characterEncoding=UTF8
    username: root
    password: root
#  redis:
#    host: 192.168.11.129
  jpa:
    database: Mysql
    show-sql: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
#  rabbitmq:
#    host: 192.168.11.129
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
