server:
  port: 9005
spring:
#  rabbitmq:
#    host: 192.168.11.129
  application:
    name: qian-an-spit
  data:
    mongodb:
      host: 192.168.11.129
      database: spitdb
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
  instance:
    prefer-ip-address: true
